services:
  app:
    build: .
    container_name: ${CONTAINER_NAME_APP}
    restart: unless-stopped
    env_file:
      - .env
      
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./app:/app
      - /app/venv
    depends_on:
        oracle:
          condition: service_healthy
    networks:
      - ecommerce_network

  nginx:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME_NGINX}
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - ecommerce_network

  redis:
    image: redis:alpine
    container_name: ${CONTAINER_REDIS_NAME}
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - ecommerce_network

  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: ${CONTAINER_DB_NAME}
    restart: unless-stopped
    env_file: 
      - .env

    ports:
      - "${ORACLE_DB_PORT}:1521"

    volumes:
      - ~/lab/docker/oracle/oradata:/opt/oracle/oradata 
      - ~/lab/docker/oracle/diag:/opt/oracle/diag 
      - ~/lab/docker/oracle/dbs:/opt/oracle/dbs
    
    networks:
      - ecommerce_network

    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/${ORACLE_DB} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

networks:
  ecommerce_network:
    driver: bridge